/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ADD: typeof import('@arco-design/web-vue')['DD']
  const AFTER: typeof import('@arco-design/web-vue')['FTER']
  const ALIAS: typeof import('@arco-design/web-vue')['LIAS']
  const ALL: typeof import('@arco-design/web-vue')['LL']
  const ALTER: typeof import('@arco-design/web-vue')['LTER']
  const AND: typeof import('@arco-design/web-vue')['ND']
  const ANTI: typeof import('@arco-design/web-vue')['NTI']
  const ANY: typeof import('@arco-design/web-vue')['NY']
  const ARRAY: typeof import('@arco-design/web-vue')['RRAY']
  const ARROW: typeof import('@arco-design/web-vue')['RROW']
  const AS: typeof import('@arco-design/web-vue')['S']
  const ASCENDING: typeof import('@arco-design/web-vue')['SCENDING']
  const ASOF: typeof import('@arco-design/web-vue')['SOF']
  const AST: typeof import('@arco-design/web-vue')['ST']
  const ASTERISK: typeof import('@arco-design/web-vue')['STERISK']
  const ASYNC: typeof import('@arco-design/web-vue')['SYNC']
  const ATTACH: typeof import('@arco-design/web-vue')['TTACH']
}
